@startuml
'left to right direction
skinparam actorStyle awesome

Class "Deck" {

Cards[20]: Flashcard

}


Class "Flashcard" {

front: Card
back: Card

}

Class "Card" {

card_text: Up to 50 utf-8 characters
card_img: a .jpg file
card_background: RGB color in hex #RRGGBB

}

@enduml
